app:
  build: .
  volumes:
    - .:/opt/application
    - /opt/application/node_modules
  ports:
   - "3000"
  environment:
    - NODE_ENV=development
    - NODE_HOT_RELOAD=1
  command: bin/dev_start.sh
